### PR TITLE
Modern frontend build

### PR DESCRIPTION
**Pull request by JasonElkin**
Dealing wtih #35 really needs a full replacement of the FE build process. It's a bit of a chunky task so I've started a draft.

Shout if you've got any questions.

So far I've:
- Tidied up the FE assets
- Removed the jQuery dependency
- Replaced Time Ago dependency
- Moved FE source files out of wwwroot
- Replaced gulp with Vite
  - ESM'd all the things
  -  Integrated with Razor
- Updated GH actions

### CODE REVIEW

**Comment by OwainWilliams** [comment]
Amazing!! Thanks for looking in to this!

**Comment by JasonElkin** [comment]
We now have a working Vite build. I've added https://github.com/Eptagone/Vite.AspNetCore which should make the DX a bit friendlier for backend/C# devs as `npm run dev` and proxying etc. will run in development so long as node.js and node modules are installed.

I could do with someone else checking out this branch in it's current state and making sure that the frontend behaves as expected. @OwainWilliams @glombek are you able to take a look?

Once that's done I can look at making the CI/CD builds work.

**Comment by glombek** [comment]
Runs out the box for me 😄

**Comment by OwainWilliams** [comment]
Great stuff! Thanks guys. 

If we need anything changed in the pipelines @AaronSadlerUK might be able to help out.

**Comment by JasonElkin** [comment]
There are still some FE improvements that can be made and approaches that can be improved or tidied up, but this is already a pretty chunky PR.

**Pull request merged**
